### ISSUE TITLE
Support tokens in player class

### ISSUE THREAD

**Issue by Ekinoxx0** [Paradigm-MP/oof#30]
Hello, there is a new type of "identifiers" that could be useful for developers.

These tokens are more clearly explained in this original commit : [Commit](https://github.com/citizenfx/fivem/commit/f52b4b994a316e1f89423b97c92d73b624bea731)

This is very low priority because we could very easily get them without the Player class, but exposing them in their specifics methods could expose them to more developers that don't know about this beautiful system.

Natives for references :
 - GetNumPlayerTokens(playerSrc)
 - GetPlayerToken(playerSrc, index)

**Comment by benank** [comment]
Thanks! Yeah that's a great addition for the Player class.

**Comment by benank** [comment]
[Added!](https://github.com/Paradigm-MP/oof/commit/44037ecab27b3298f0e900f36df4d02e995789d8)
